version: '3'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file: .env
    command: python3 manage.py runserver 0.0.0.0:8000

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_PASSWORD=eddy-automl
      - MYSQL_USER=eddy-automl
      - MYSQL_DATABASE=eddy-automl-db
    ports:
      - 3306:3306

