# Generated by Django 2.2.10 on 2020-04-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200411_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='automljob',
            name='job_name',
            field=models.CharField(default='job', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automljob',
            name='status',
            field=models.IntegerField(choices=[('RUNNING', 0), ('STOPPED', 1), ('FAILED', -1)], default=1),
            preserve_default=False,
        ),
    ]
