# Generated by Django 2.2.10 on 2020-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200414_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automljob',
            name='status',
            field=models.IntegerField(choices=[('RUNNING', 0), ('STOPPED', 1), ('FAILED', -1)]),
        ),
    ]
