# Generated by Django 2.2.10 on 2020-04-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200415_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automljob',
            name='target_column',
            field=models.IntegerField(),
        ),
    ]
