# Generated by Django 2.2.10 on 2020-04-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200415_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='automljob',
            name='pod_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
