# Generated by Django 2.2.10 on 2020-04-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_automljob_pod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automljob',
            name='status',
            field=models.IntegerField(choices=[('WAITING', 0), ('RUNNING', 1), ('STOPPED', 2), ('FAILED', -1)]),
        ),
    ]
